flask-app/app/models.py
from . import db
from datetime import datetime


class ExampleModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(256))
    email = db.Column(db.String(256))
    favorite_food = db.Column(db.String(128))
    timestamp = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    def __init__(self, username, email, favorite_food):
        self.username = username
        self.email = email
        self.favorite_food = favorite_food

    def __repr__(self):
        return f"{self.id} {self.username} {self.email} {self.favorite_food} {self.timestamp}"

flask-app/app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, EmailField
from wtforms.validators import InputRequired, EqualTo, Email
from sqlalchemy.exc import OperationalError
from ..models import ExampleModel


class ExampleForm(FlaskForm):
    # Resuable array of validators
    basic_validator = [InputRequired()]
    field1 = StringField("field1:", basic_validator)
    select_filed = SelectField("filed2:", basic_validator)
    email = EmailField(
        "email:",
        validators=[
            InputRequired(),
            EqualTo("confirm_email", message="Emails must match"),
            Email(),
        ],
    )
    confirm_email = EmailField("confirm_email:", basic_validator)
    submit = SubmitField("Submit")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Pull values from database for dropdown
        try:
            db_values = [x.favorite_food for x in ExampleModel.query.all()]
        except OperationalError:
            db_values = []

        # Initial values if database has no values
        select_field_values = [
            ("", "--Select a Value --"),
            ("Chilli", "Chilli"),
            ("Hamburgers", "Hamburgers"),
            ("Hot Dogs", "Hot Dogs"),
            ("Pizza", "Pizza"),
        ]

        for value in db_values:
            select_field_values.append((value, value))

        select_field_values.sort()

        self.select_filed.choices = select_field_values

flask-app/app/__init__.py
from flask import Flask
from config import config
from flask_sqlalchemy import SQLAlchemy
import logging

# from flask_migrate import Migrate


db = SQLAlchemy()
# migrate = Migrate()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # Docker container mixes testing logs with dev server logs
    # when server is run in background, just disabled them to prevent this
    if config_name == "testing":
        werkzeug_log = logging.getLogger("werkzeug")
        werkzeug_log.disabled = True

    # Plug-in inits
    db.init_app(app)
    # migrate.init_app(app, db)

    # import blueprints
    from .main import main as main_blueprint

    app.register_blueprint(main_blueprint, url_prefix="/")

    return app

flask-app/app/main/__init__.py
from flask import Blueprint

main = Blueprint("main", __name__)

from . import views, errors

flask-app/app/main/views.py
from flask import render_template, redirect, url_for, flash, current_app
from .forms import ExampleForm
from . import main


@main.route("/")
def home():
    return render_template("main/index.html")


@main.route("/form", methods=["GET", "POST"])
def example_form():
    example_form = ExampleForm()

    if example_form.validate_on_submit():
        return redirect(url_for("main.submission_success"))

    else:
        for error_key in example_form.errors:
            for error_value in example_form.errors[error_key]:
                current_app.logger.info("%s", error_value)
                flash(error_value)

    return render_template("main/form.html", form=example_form)


@main.route("/submission-success")
def submission_success():
    return render_template("main/success.html")

flask-app/app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask App | {% block title %} {% endblock %}</title>
</head>

<body>
    <nav>
        <ul>
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('main.example_form') }}">WTF Forms Example</a></li>
        </ul>
    </nav>
    {% for message in get_flashed_messages() %}
    <div id="example-alert" style="background-color: red;" role="alert">
        {{message}}
    </div>
    {% endfor %}
    <main>
        {% block main_content %}
        {% endblock %}
    </main>
    <footer>
        © Copyright Your Entity
    </footer>
</body>

</html>

flask-app/app/templates/main/form.html
{% extends "main/base.html" %}
{% block title %}Example Form{% endblock %}

{% block main_content %}

    <form id="example-form" method="POST">
        {{ form.hidden_tag() }}

        <div>
            {{ form.field1.label }} {{ form.field1(class="form-field") }}
        </div>

        <div>
            {{ form.select_filed.label }} {{ form.select_filed(class="form-field") }}
        </div>

        <div>
            {{ form.email.label }} {{ form.email(class="form-field") }}
        </div>

        <div>
            {{ form.confirm_email.label }} {{ form.confirm_email(class="form-field") }}
        </div>


        {{form.submit(class="submit-button")}}
    </form>
{% endblock %}

flask-app/app/templates/main/index.html
{% extends "main/base.html" %}
{% block title %}Home{% endblock %}

{% block main_content %}
<h1 id="welcome-message">Hello</h1>
{% endblock %}

flask-app/app/templates/main/success.html
{% extends "main/base.html" %}
{% block title %}Success{% endblock %}

{% block main_content %}
<h1 id="success-message">Success</h1>
{% endblock %}